version: "3"

services:
  namenode:
    image: nogala/hadoop-namenode:2.8.5
    container_name: namenode
    hostname: namenode
    ports:
      - 50070:50070
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode:
    image: nogala/hadoop-datanode:2.8.5
    container_name: datanode
    hostname: datanode
    ports:
      - 50075:50075
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    env_file:
      - ./hadoop.env
  
  resourcemanager:
    image: nogala/hadoop-resourcemanager:2.8.5
    container_name: resourcemanager
    hostname: resourcemanager
    ports:
      - 8088:8088
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
      - ./hadoop.env

  nodemanager:
    image: nogala/hadoop-nodemanager:2.8.5
    container_name: nodemanager
    hostname: nodemanager
    ports:
      - 8042:8042
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50010 resourcemanager:8088"
    env_file:
      - ./hadoop.env
  
  historyserver:
    image: nogala/hadoop-historyserver:2.8.5
    container_name: historyserver
    hostname: historyserver
    ports:
      - 8188:8188
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50010 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
  
volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
